AppointmentBooking.Web/Controllers/AppointmentController.cs
using Appointment_Booking.Data.Dto;
using Appointment_Booking.Service.Services.AppointmentService;
using Appointment_Booking.Service.Services.CampanyService;
using Appointment_Booking.Service.Services.UserService;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Appointment_Booking.Web.Controllers
{
    public class AppointmentController : Controller
    {

        private readonly IAppointmentService appointmentService;
        private readonly ICampanyService campanyService;
        private readonly IUserService userService;

        public AppointmentController(IAppointmentService appointmentService, ICampanyService campanyService, IUserService userService)
        {
            this.appointmentService = appointmentService;
            this.campanyService = campanyService;
            this.userService = userService;
        }

        public IActionResult Index(int page, int? campanyId, string userId, DateTime? date)
        {
            string dateAfterFormat = "";

            if (date != null)
                dateAfterFormat = ((DateTime)date).ToString("yyyy/MM/dd");


            var appointmentsViewModel = appointmentService.GetAllAppointments(page, campanyId, userId, dateAfterFormat);

            var campaniesViewModel = campanyService.GetAllCampanies();
            var usersViewModel = userService.GetAllUsers();


            ViewBag.users = usersViewModel;
            ViewBag.campanies = campaniesViewModel;

            ViewBag.userId = userId;
            ViewBag.campanyId = campanyId;
            ViewBag.date = date;

            return View(appointmentsViewModel);
        }

        [HttpGet]
        public IActionResult AddAppointment()
        {

            var campaniesViewModel = campanyService.GetAllCampanies();
            var usersViewModel = userService.GetAllUsers();

            ViewBag.users = usersViewModel;
            ViewBag.campanies = campaniesViewModel;

            return View();
        }


        [HttpPost]
        public IActionResult AddAppointment(AppointmentDto dto)
        {
            appointmentService.AddAppointment(dto);

            return RedirectToAction("Index");
        }

        [HttpGet]

        public IActionResult EditAppointment(int id)
        {

            var campaniesViewModel = campanyService.GetAllCampanies();
            var usersViewModel = userService.GetAllUsers();
            var appointmentViewModel = appointmentService.GetAppointment(id);

            ViewBag.users = usersViewModel;
            ViewBag.campanies = campaniesViewModel;
            ViewBag.appointment = appointmentViewModel;

            return View();
        }

        [HttpPost]
        public IActionResult EditAppointment(AppointmentDto dto)
        {

            appointmentService.EditAppointment(dto);

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult DeleteAppointment(int id)
        {

            appointmentService.DeleteAppointment(id);


            return RedirectToAction("Index");
        }

    }
}

AppointmentBooking.Web/Controllers/CampanyController.cs
using Appointment_Booking.Data.Dto;
using Appointment_Booking.Data.Enums;
using Appointment_Booking.Service.Services.CampanyService;
using Microsoft.AspNetCore.Mvc;

namespace Appointment_Booking.Web.Controllers
{
    public class CampanyController : Controller
    {

        private readonly ICampanyService campanyService;
        


        public CampanyController (ICampanyService campanyService )
        {

            this.campanyService = campanyService;
           
        }

        public IActionResult Index(int id , string name)
        {
            var campanies = campanyService.GetCampanies(id,name);

            ViewBag.name = name;

            return View(campanies);
        }

        [HttpGet]
        public IActionResult AddCampany()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCampany (CampanyDto dto)
        {

            campanyService.AddCampany(dto);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditCampany (int id)
        {
            ViewBag.id = id;

            ViewBag.campany = campanyService.GetCampany(id);

            return View();
        }

        [HttpPost]
        public IActionResult EditCampany(CampanyDto dto)
        {

            campanyService.EditCampany(dto);

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult DeleteCampany(int id)
        {

            campanyService.DeleteCampany(id);

            return RedirectToAction("Index");
        }

    }
}

AppointmentBooking.Web/Controllers/UserController.cs
using Appointment_Booking.Data.Dto;
using Appointment_Booking.Data.Enums;
using Appointment_Booking.Service.Services.UserService;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Appointment_Booking.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;


        public UserController (IUserService userService)
        {
            this.userService = userService;
     
        }


        public IActionResult Index(int id,string name , Gender? gender)
        {
            var users = userService.GetUsers(id,name,gender);

            ViewBag.name = name;
            ViewBag.gender = gender;

            return View(users);
        }

       

        [HttpGet]
        public IActionResult AddUser()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddUser(UserDto dto)
        {

            bool result = await userService.AddUser(dto);
            
            return RedirectToAction(result ? "Index" : "AddUser") ;
        }


        [HttpGet]
        public IActionResult EditUser(string id)
        {
            var userViewModel = userService.GetUser(id);
            ViewBag.user = userViewModel;
            return View();
        }

        [HttpPost]
        public IActionResult EditUser(UserDto dto)
        {

            userService.EditUser(dto);

            return RedirectToAction("Index");
        }

        public IActionResult DeleteUser(string id)
        {

            userService.DeleteUser(id);

            return RedirectToAction("Index");
        }

    }
}

AppointmentBooking.Web/Views/Appointment/AddAppointment.cshtml
@model Appointment_Booking.Data.Dto.AppointmentDto

@{
    ViewData["Title"] = "Add Appointment";
    List<UserViewModel> users = ViewBag.users;
    List<CampanyViewModel> campanies = ViewBag.campanies;
}

<br />

<div class="row" style="margin-left:2%;margin-right:2%;">
    <div class="col-md-12 col-md-offset-12">

        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Add Campany</h3>
            </div>

            <form asp-action="AddAppointment" method="post">
                <div class="card-body">

                    <div class="form-group">
                        <label asp-for="CampanyId" class="control-label"></label>

                        <select asp-for="CampanyId" class="form-control">

                            @foreach (CampanyViewModel campany in campanies)
                            {
                                <option value="@campany.Id">@campany.Name</option>
                            }

                        </select>
                    </div>

                    <div class="form-group">
                        <label asp-for="UserId" class="control-label"></label>

                        <select asp-for="UserId" class="form-control">

                            @foreach (UserViewModel user in users)
                            {
                                <option value="@user.Id">@{var fullName = $"{user.FirstName} {user.LastName}"; } @fullName</option>
                            }

                        </select>
                    </div>



                    <div class="form-group">
                        <label asp-for="BookingDateTime" class="control-label"></label>
                        <input asp-for="BookingDateTime" type="datetime" class="form-control" />
                        <span asp-validation-for="BookingDateTime" class="text-danger"></span>

      

                    </div>

                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>


                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-1">
                            <button type="submit" class="btn btn-success">Save</button>
                        </div>
                        <div class="col-md-1">
                            <a asp-action="Index" class="btn btn-primary">Cancel</a>
                        </div>
                    </div>

                </div>
            </form>
        </div>

    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}



}

AppointmentBooking.Web/Views/Appointment/EditAppointment.cshtml
@model Appointment_Booking.Data.Dto.AppointmentDto

@{
    ViewData["Title"] = "Edit Appointment";
    List<UserViewModel> users = ViewBag.users;
    List<CampanyViewModel> campanies = ViewBag.campanies;
    AppointmentViewModel appointment = ViewBag.appointment;
}

<br />

<div class="row" style="margin-left:2%;margin-right:2%;">
    <div class="col-md-12 col-md-offset-12">

        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Add Campany</h3>
            </div>

            <form asp-action="EditAppointment" method="post">
                <div class="card-body">

                    <div class="form-group">
                        <label asp-for="CampanyId" class="control-label"></label>

                        <select asp-for="CampanyId" class="form-control">

                            @foreach (CampanyViewModel campany in campanies)
                            {
                                <option value="@campany.Id">@campany.Name</option>
                            }

                        </select>
                    </div>

                    <div class="form-group">
                        <label asp-for="UserId" class="control-label"></label>

                        <select asp-for="UserId" class="form-control">

                            @foreach (UserViewModel user in users)
                            {
                                <option value="@user.Id">@{var fullName = $"{user.FirstName} {user.LastName}"; } @fullName</option>
                            }

                        </select>
                    </div>



                    <div class="form-group">
                        <label asp-for="BookingDateTime" class="control-label"></label>
                        <input asp-for="BookingDateTime" value="@appointment.BookingDateTime" type="datetime" class="form-control" />
                        <span asp-validation-for="BookingDateTime" class="text-danger"></span>



                    </div>

                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" value="@appointment.BookingDateTime" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>


                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-1">
                            <button type="submit" class="btn btn-success">Save</button>
                        </div>
                        <div class="col-md-1">
                            <a asp-action="Index" class="btn btn-primary">Cancel</a>
                        </div>
                    </div>

                </div>
            </form>
        </div>

    </div>
</div>

AppointmentBooking.Web/Views/Appointment/Index.cshtml
@model PagingViewModel<AppointmentViewModel>

@{
    ViewData["Title"] = "Appointments";

    List<UserViewModel> users = ViewBag.users;
    List<CampanyViewModel> campanies = ViewBag.campanies;

    var campanyId = ViewBag.campanyId;
    var userId = ViewBag.userId;
    var date = ViewBag.date;

    var nextPage = Model.CurrentPage + 1;
    var previousPage = Model.CurrentPage - 1;

}

<br />
<br />
<br />

<div class="row" style="margin-right:20px; margin-left:20px;">
    <div class="col-md-auto">
        <div class="card" style="padding:0px 10px 0px 10px">

            <label style="padding: 10px 0px 0px 15px;">Search Filter</label>

            <div class="row">

                <div class="col-md-10">

                    <form method="get" asp-action="Index">

                        <div class="row" style="padding-left: 10px;">



                            <div class="col-md-3">
                                <div class="form-group">
                                    <select name="campanyId" class="form-control">

                                        @if (campanyId != null)
                                        {


                                            @foreach (var campany in campanies)
                                            {
                                                @if (campanyId == campany.Id)
                                                {
                                                    <option selected="selected" value="@campany.Id">@campany.Name</option>
                                                }
                                                else
                                                {
                                                    <option value="@campany.Id">@campany.Name</option>
                                                }

                                            }

                                        }
                                        else
                                        {
                                            <option value="" selected="selected" disabled>Select Campany</option>

                                            @foreach (var campany in campanies)
                                            {
                                                <option value="@campany.Id">@campany.Name</option>
                                            }

                                        }

                                    </select>
                                </div>
                            </div>


                            <div class="col-md-3">
                                <div class="form-group">
                                    <select name="userId" class="form-control">

                                        @if (userId != null)
                                        {


                                            @foreach (var user in users)
                                            {
                                                @if (userId == user.Id)
                                                {
                                                    <option selected="selected" value="@user.Id">
                                                        @{ var fullName = $"{user.FirstName} {user.LastName}";
                                                        } @fullName
                                                    </option>
                                                }

                                                else
                                                {
                                                    <option value="@user.Id">
                                                        @{ var fullName = $"{user.FirstName} {user.LastName}";
                                                        } @fullName
                                                    </option>
                                                }
                                            }
                                        }

                                        else
                                        {
                                            <option value="" selected="selected" disabled>Select User</option>

                                            @foreach (var user in users)
                                            {
                                                <option value="@user.Id">
                                                    @{ var fullName = $"{user.FirstName} {user.LastName}";
                                                    } @fullName
                                                </option>
                                            }
                                        }

                                    </select>
                                </div>
                            </div>


                            <div class="col-md-3">
                                <div class="form-group">

                                    @if (date != null)
                                    {
                                        <input class="form-control" placeholder="Appointment Date" value="@date" name="date" type="datetime" />

                                    }
                                    else
                                    {

                                        <input class="form-control" placeholder="Appointment Date" value="@DateTime.Today.ToString("yyyy/MM/dd")" name="date" type="datetime" />

                                    }
                                </div>
                            </div>


                            <div class="col-md-1">
                                <input type="submit" value="Apply Filter" class="btn btn-primary" />
                            </div>

                            @if (userId != null || campanyId != null || date != null)
                            {
                                <div class="col-md-1">
                                    <div class="row" style="padding-left:60px;">
                                        <a href="~/Appointment/Index/" class="btn btn-secondary">Clear</a>
                                    </div>
                                </div>
                            }




                        </div>

                    </form>

                </div>



            </div>

            <table class="table table-striped">
                <thead>
                    <tr>

                        <th>
                            Campany Name
                        </th>

                        <th>
                            User Name
                        </th>
                        <th>
                            BookingDateTime
                        </th>
                        <th>
                            Description
                        </th>

                        <th></th>
                        

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Data)
                    {
                        <tr>

                            <td>
                                @Html.DisplayFor(modelItem => item.CampanyName)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.UserName)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.BookingDateTime)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>

                                <div class="row" style="padding-right:27px">
                                    <div class="col-md-6">
                                        <a class="btn btn-warning" href="~/Appointment/EditAppointment/@item.Id">Edit</a>

                                    </div>

                                    <div class="col-md-1">

                                        <a class="btn btn-danger" href="~/Appointment/DeleteAppointment/@item.Id">Delete</a>
                                    </div>

                                </div>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>



            <div class="col-md-12" style="margin-top:20px;padding:0px 30px 0px 30px;">


                <a href="~/Appointment/AddAppointment/" class="btn btn-success" style="float:left">Add Appointment</a>

                <!-- Pagination Nav -->

                <nav style="margin:0px 0px 0px 0px;display: flex; justify-content: flex-end;">
                    <ul class="pagination">

                        @if (Model.CurrentPage > 1)
                        {

                            <li class="page-item ">
                                <span class="page-link"><a href="~/Appointment/index/@previousPage">Previous</a></span>
                            </li>

                        }
                        else
                        {
                            <li class="page-item disabled">
                                <span class="page-link">Previous</span>
                            </li>
                        }


                        @for (int i = 1; i <= Model.PagesCount; i++)
                        {
                            if (i == Model.CurrentPage)
                            {
                                <li class="page-item active">
                                    <span class="page-link">
                                        <a style="color:white;" href="~/Appointment/index/@i">@i</a>

                                        <span class="sr-only">(current)</span>
                                    </span>
                                </li>
                            }
                            else
                            {
                                <li class="page-item"><a class="page-link" href="~/Appointment/index/@i">@i</a></li>
                            }
                        }

                        @if (Model.CurrentPage < Model.PagesCount)
                        {
                            <li class="page-item">
                                <a class="page-link" href="~/Appointment/index/@nextPage">Next</a>
                            </li>
                        }
                        else
                        {
                            <li class="page-item disabled">
                                <a class="page-link">Next</a>
                            </li>
                        }


                    </ul>
                </nav>

            </div>




        </div>
    </div>
</div>

AppointmentBooking.Web/Views/Campany/AddCampany.cshtml
@model Appointment_Booking.Data.Dto.CampanyDto

@{
    ViewData["Title"] = "AddCampany";
}

<br />

<div class="row" style="margin-left:2%;margin-right:2%;">
    <div class="col-md-12 col-md-offset-12">

        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Add Campany</h3>
            </div>
         
            <form asp-action="AddCampany" method="post">
                <div class="card-body">

                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber" class="control-label"></label>
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Address.CountryName" class="control-label"></label>
                        <input asp-for="Address.CountryName" class="form-control" />
                        <span asp-validation-for="Address.CountryName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Address.CityName" class="control-label"></label>
                        <input asp-for="Address.CityName" class="form-control" />
                        <span asp-validation-for="Address.CityName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Address.StreetName" class="control-label"></label>
                        <input asp-for="Address.StreetName" class="form-control" />
                        <span asp-validation-for="Address.StreetName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Address.Latitude" class="control-label"></label>
                        <input asp-for="Address.Latitude" class="form-control" />
                        <span asp-validation-for="Address.Latitude" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Address.Longtitude" class="control-label"></label>
                        <input asp-for="Address.Longtitude" class="form-control" />
                        <span asp-validation-for="Address.Longtitude" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Website" class="control-label"></label>
                        <input asp-for="Website" class="form-control" />
                        <span asp-validation-for="Website" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="WorkStart" class="control-label"></label>
                        <input asp-for="WorkStart" class="form-control" />
                        <span asp-validation-for="WorkStart" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="WorkEnd" class="control-label"></label>
                        <input asp-for="WorkEnd" class="form-control" />
                        <span asp-validation-for="WorkEnd" class="text-danger"></span>
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-1">
                            <button type="submit" class="btn btn-success">Save</button>
                        </div>
                        <div class="col-md-1">
                            <a asp-action="Index" class="btn btn-primary">Cancel</a>
                        </div>
                    </div>
                    
                </div>
            </form>
        </div>

    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppointmentBooking.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Appointment_Booking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Appointment_Booking.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Campany" asp-action="Index">Campanies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Appointment_Booking- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>